
target ‘BobApp' do
  pod ‘Pulsator’
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare', :git => 'https://github.com/1amageek/facebook-sdk-swift'
pod 'KeychainSwift', '~> 9.0'
use_frameworks!
end
