project 'BobApp.xcodeproj'
target 'BobApp' do
	pod 'Pulsator'
	pod 'FacebookCore'
	pod 'FacebookLogin'
	pod 'KeychainSwift', '~> 9.0'
	pod 'SQLite.swift'
    pod 'SwiftyJSON'
    pod 'Alamofire', '~> 4.5'
    pod 'SDWebImage', '~> 4.0'
use_frameworks!
end
